name: HypixelMigratorAddon
version: '${project.version}'
main: me.harsh.hypixelmigratoraddon.HypixelMigratorPlugin
api-version: 1.13
commands:
  migrate:
    aliases:
      - migrate
      - mig
    description: migrate command
    usage: /migrate